### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by fil512** [geni/geni-gedcom#9]
It successfully parsed my gedcom file and I picked me, but about 5 seconds after I clicked "choose" I got the following stack trace.  The tracker says:
{"progress":1,"status":"importing","profile_count":3429}

Exception in thread "Thread-12" java.lang.NullPointerException
        at clojure.lang.Numbers.ops(Numbers.java:942)
        at clojure.lang.Numbers.add(Numbers.java:126)
        at geni.gedcom.import$import_tree.invoke(import.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:603)
        at clojure.core$partial$fn__4070.doInvoke(core.clj:2343)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.core$reductions$fn__6175.invoke(core.clj:6381)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:60)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:587)
        at clojure.core$next.invoke(core.clj:64)
        at geni.gedcom.web.models.api$import_records$fn__4243.invoke(api.clj:108)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Unknown Source)

**Comment by jrunning** [comment]
I'm getting the exact same error, except that the web interface just says `{"profile_count":377}`.
